const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const palette=[['Nền sáng','#F7F7FA'],['Kính sáng','#FFFFFF9E'],['Chữ','#111111'],['Chữ phụ','#596170'],['Cyan','#00C2FF'],['Blue','#4F8CFF'],['Indigo','#7C5CFF'],['Purple','#D946EF'],['Pink','#FF5E8A']];
const demo=[['@linh.anh','Shop ơi kính này có dễ dán không ạ?',1],['@hoangnam88','Giá này đã gồm ship chưa shop?',1],['@meocon_07','Có loại cho máy đời cũ không vậy?',1],['@huyen.trang','Mua 2 cái có ưu đãi gì thêm không?',1],['@anhkhoa','Dùng lâu cảm ứng có bị đơ không?',1],['@thanhha','Chốt đơn ở đâu thế ạ?',1],['@duongpham','Nhìn xinh á 😍',0]];
const seed=[{id:'p1',name:'Kính cường lực 9H',price:'99.000đ',offer:'Freeship theo chương trình sàn',benefits:'Phủ kín màn hình\nCảm ứng mượt\nViền gọn, dễ lắp',audience:'Người cần bảo vệ màn hình hằng ngày',guard:'Không nói chống vỡ 100%\nKhông bịa tương thích máy'}];
const S={run:false,mode:localStorage.getItem('lion_mode')||'manual',tone:localStorage.getItem('lion_tone')||'friendly',comments:[],selected:null,spoken:0,timer:null,products:readJSON('lion_products',seed),active:localStorage.getItem('lion_active')||'p1',edit:null,provider:localStorage.getItem('lion_provider')||'openai',model:localStorage.getItem('lion_model')||'gpt-5.6-luna',voice:localStorage.getItem('lion_tts_voice')||'lion-conversation',customVoiceId:localStorage.getItem('lion_custom_voice_id')||'',rate:Number(localStorage.getItem('lion_rate')||1),theme:localStorage.getItem('lion_theme')||'light',history:readJSON('lion_history',[]),audio:null,audioUrl:null,queue:Promise.resolve(),sampleUrl:null};
function readJSON(k,f){try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),3200)}
function persist(){localStorage.setItem('lion_products',JSON.stringify(S.products));localStorage.setItem('lion_active',S.active||'');localStorage.setItem('lion_provider',S.provider);localStorage.setItem('lion_model',S.model);localStorage.setItem('lion_tts_voice',S.voice);localStorage.setItem('lion_custom_voice_id',S.customVoiceId);localStorage.setItem('lion_rate',S.rate);localStorage.setItem('lion_theme',S.theme);localStorage.setItem('lion_mode',S.mode);localStorage.setItem('lion_tone',S.tone);localStorage.setItem('lion_history',JSON.stringify(S.history.slice(0,50)))}
function renderPalette(){$('#paletteList').innerHTML=palette.map(([n,c])=>`<div class="swatch"><i style="background:${c}"></i><b>${esc(n)}</b><code>${c}</code></div>`).join('')}
function applyTheme(){document.body.classList.toggle('dark',S.theme==='dark');$$('#themeSwitch button').forEach(b=>b.classList.toggle('active',b.dataset.theme===S.theme));document.querySelector('meta[name="theme-color"]').setAttribute('content',S.theme==='dark'?'#09090B':'#F7F7FA')}
function switchView(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const meta={studio:['Live Studio','AI hỗ trợ trả lời bình luận và bán hàng live tự nhiên hơn.'],products:['Sản phẩm','Nguồn dữ liệu thật để Lion AI không bịa.'],settings:['Cài đặt','AI, TTS, file giọng mẫu và bộ dò giọng tiếng Việt.']}[v];$('#pageTitle').textContent=meta[0];$('#pageSub').textContent=meta[1]}
function metrics(){$('#mBot').textContent=S.run?'Đang chạy':'Sẵn sàng';$('#mComments').textContent=S.comments.length;$('#mIntent').textContent=S.comments.filter(x=>x.intent).length;$('#mSpoken').textContent=S.spoken}
function currentProduct(){return S.products.find(x=>x.id===S.active)||S.products[0]}
function syncProduct(){const p=currentProduct();$('#prodName').textContent=p?.name||'Chưa có sản phẩm';$('#prodMeta').textContent=p?`${p.price||'Chưa nhập giá'} · ${p.offer||'Chưa nhập ưu đãi'}`:'Thêm dữ liệu để AI không bịa.'}
function renderComments(){const r=$('#comments');if(!S.comments.length){r.innerHTML='<div class="empty">Bấm Bắt đầu bot hoặc Demo comment để thử.</div>';return}r.innerHTML=S.comments.map(c=>`<div class="comment ${S.selected?.id===c.id?'active':''}" data-id="${esc(c.id)}"><b>${esc(c.user)}</b><p>${esc(c.text)}</p>${c.intent?'<span class="intent">Ý định mua / hỏi sản phẩm</span>':''}</div>`).join('');$$('.comment',r).forEach(el=>el.onclick=()=>selectComment(S.comments.find(c=>c.id===el.dataset.id)))}
function renderHistory(){const r=$('#historyList');if(!S.history.length){r.innerHTML='<div class="empty">Chưa có lịch sử chat.</div>';return}r.innerHTML=S.history.map(h=>`<div class="history-item"><b>${esc(h.user)}</b><p><strong>Khách:</strong> ${esc(h.ask)}</p><p><strong>Lion AI:</strong> ${esc(h.reply)}</p><small>${esc(h.time)}</small></div>`).join('')}
function addHistory(c,reply){S.history.unshift({user:c?.user||'@khách',ask:c?.text||'',reply,time:new Date().toLocaleString('vi-VN')});S.history=S.history.slice(0,50);persist();renderHistory()}
function renderProducts(){const r=$('#productList');if(!S.products.length){r.innerHTML='<div class="empty">Chưa có sản phẩm.</div>';syncProduct();return}r.innerHTML=S.products.map(p=>`<div class="product-item ${p.id===S.active?'active':''}" data-id="${esc(p.id)}"><b>${esc(p.name)}</b><span>${esc(p.price||'')}</span><small>${esc((p.benefits||'').split('\n')[0]||'Chưa có mô tả')}</small></div>`).join('');$$('.product-item',r).forEach(el=>el.onclick=()=>loadProduct(el.dataset.id));syncProduct()}
function loadProduct(id){const p=S.products.find(x=>x.id===id);if(!p)return;S.edit=id;S.active=id;$('#pName').value=p.name||'';$('#pPrice').value=p.price||'';$('#pOffer').value=p.offer||'';$('#pAudience').value=p.audience||'';$('#pBenefits').value=p.benefits||'';$('#pGuard').value=p.guard||'';persist();renderProducts()}
function newProduct(){S.edit=null;['pName','pPrice','pOffer','pAudience','pBenefits','pGuard'].forEach(id=>$('#'+id).value='');$('#pName').focus()}
function saveProduct(){const name=$('#pName').value.trim();if(!name)return toast('Hãy nhập tên sản phẩm.');const p={id:S.edit||('p'+Date.now()),name,price:$('#pPrice').value.trim(),offer:$('#pOffer').value.trim(),audience:$('#pAudience').value.trim(),benefits:$('#pBenefits').value.trim(),guard:$('#pGuard').value.trim()};const i=S.products.findIndex(x=>x.id===p.id);if(i>=0)S.products[i]=p;else S.products.push(p);S.edit=p.id;S.active=p.id;persist();renderProducts();toast('Đã lưu sản phẩm.')}
function deleteProduct(){if(!S.edit)return toast('Chọn sản phẩm cần xóa.');S.products=S.products.filter(x=>x.id!==S.edit);S.active=S.products[0]?.id||'';S.edit=null;persist();newProduct();renderProducts();toast('Đã xóa sản phẩm.')}
function addComment(){const a=demo[Math.floor(Math.random()*demo.length)],c={id:String(Date.now()+Math.random()),user:a[0],text:a[1],intent:!!a[2]};S.comments.unshift(c);S.comments=S.comments.slice(0,40);renderComments();metrics();if(S.mode==='auto'&&S.run&&c.intent)generateReply(c,true)}
function selectComment(c){if(!c)return;S.selected=c;renderComments();$('#selected').innerHTML=`<b>${esc(c.user)}</b> — ${esc(c.text)}`;generateReply(c,false)}
function ctx(p){return `Tên: ${p?.name||'chưa có'}\nGiá: ${p?.price||'chưa có'}\nƯu đãi: ${p?.offer||'chưa có'}\nĐiểm nổi bật: ${p?.benefits||'chưa có'}\nKhách phù hợp: ${p?.audience||'chưa có'}\nKhông được nói: ${p?.guard||'không có'}`}
function fallback(c,p){const t=c.text.toLowerCase();if(t.includes('ship'))return'Phí ship có thể thay đổi theo tài khoản và chương trình của sàn nha. Bạn kiểm tra ở bước đặt hàng để ra số chính xác nhất giúp mình nhé.';if(t.includes('ưu đãi')||t.includes('mua 2'))return'Ưu đãi mình chỉ nói đúng phần đang hiển thị thôi nha. Bạn kiểm tra giỏ hàng hiện tại để thấy chương trình chính xác nhất nhé.';if(t.includes('chốt')||t.includes('mua'))return'Bạn thấy phù hợp thì kiểm tra đúng phân loại và giá đang hiển thị trước khi đặt nha.';return`Với ${p?.name||'sản phẩm'}, phần nào chưa chắc mình sẽ kiểm tra để tư vấn bạn chính xác hơn nha.`}
async function askAI(prompt,purpose='general'){if(S.provider==='demo')return null;try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:S.provider,model:S.model,prompt,purpose})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'AI API error');return(d.text||'').trim()}catch(e){console.error(e);toast('AI đang tạm thời chưa phản hồi. Lion AI dùng câu dự phòng an toàn.');return null}}
async function generateReply(c,autoSpeak=false){if(!c)return toast('Hãy chọn một bình luận trước.');S.selected=c;renderComments();$('#selected').innerHTML=`<b>${esc(c.user)}</b> — ${esc(c.text)}`;$('#reply').value='AI đang nghĩ…';const p=currentProduct(),tone={friendly:'tự nhiên, khéo, ấm áp',energetic:'trẻ, gọn, năng lượng vừa đủ',premium:'tinh tế, rõ ý, có gu'}[S.tone];const prompt=`Khách ${c.user} bình luận: "${c.text}"\n${ctx(p)}\nTrả lời bằng tiếng Việt, phong cách ${tone}, 1-2 câu khoảng 20-40 từ. Không bịa. Biết quan tâm nhu cầu người tiêu dùng và CTA mềm.`;const text=await askAI(prompt,'live_reply')||fallback(c,p);$('#reply').value=text;addHistory(c,text);if(autoSpeak)enqueueSpeak(text,true)}
function stopAudio(){try{if(S.audio){S.audio.pause();S.audio=null}if(S.audioUrl){URL.revokeObjectURL(S.audioUrl);S.audioUrl=null}if('speechSynthesis'in window)speechSynthesis.cancel();$('#orb').classList.remove('speaking')}catch{}}
function enqueueSpeak(text,auto){S.queue=S.queue.then(()=>speakText(text,auto)).catch(e=>console.error(e));return S.queue}
function ttsVoicePayload(){if(S.voice==='custom')return /^voice_[A-Za-z0-9_-]{3,80}$/.test(S.customVoiceId)?S.customVoiceId:'marin';if(S.voice==='lion-conversation')return'marin';return S.voice}
async function speakText(text,auto=false){if(!text||text==='AI đang nghĩ…')return;stopAudio();$('#orb').classList.add('speaking');$('#hostState').textContent=auto?'Đang trả lời tự động':'Đang đọc câu đã duyệt';try{if(S.provider==='openai'){const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,voice:ttsVoicePayload(),speed:S.rate,preset:S.voice==='lion-conversation'?'conversation':'default'})});if(r.ok){const blob=await r.blob(),url=URL.createObjectURL(blob),a=new Audio(url);S.audio=a;S.audioUrl=url;await new Promise((resolve,reject)=>{a.onended=resolve;a.onerror=reject;a.play().catch(reject)});S.spoken++;metrics();return}}await LionVietnameseVoices.speak(text,S.rate);S.spoken++;metrics()}catch(e){toast(e.message||'Không phát được giọng Việt.')}finally{stopAudio();$('#hostState').textContent=S.run?'AI host đang trực':'Đang chờ bắt đầu'}}
function refreshVoicePicker(){const list=LionVietnameseVoices.load(),sel=$('#browserVoice'),preferred=LionVietnameseVoices.best();sel.innerHTML=list.length?list.map(v=>`<option value="${esc(v.name)}">${esc(v.name)} — ${esc(v.lang)}</option>`).join(''):'<option value="">Không tìm thấy giọng tiếng Việt</option>';if(preferred)sel.value=preferred.name;$('#voiceState').textContent=list.length?`Đã tìm thấy ${list.length} giọng Việt trên thiết bị`:'Không có voice Việt trên máy — ưu tiên OpenAI TTS';$('#voiceHelp').textContent=list.length?`Đang có ${list.length} voice Việt. Lion AI không fallback sang tiếng Anh.`:'Không tìm thấy voice vi/vi-VN. OpenAI TTS vẫn có thể đọc tiếng Việt.'}
function syncVoiceUI(){const custom=S.voice==='custom';$('#customVoiceRow').classList.toggle('show',custom);$('#customVoiceId').value=S.customVoiceId;$('#ttsVoice').value=S.voice}
function setupVoiceSample(){if(!window.LionVoiceReference)return;try{S.sampleUrl=LionVoiceReference.createUrl();$('#voiceSampleAudio').src=S.sampleUrl}catch(e){console.error(e)}}
function syncSettings(){$('#provider').value=S.provider;$('#model').value=S.model;$('#rate').value=S.rate;$('#statusChip').textContent=S.provider==='openai'?'OpenAI sẵn sàng':'Demo Mode';syncVoiceUI()}
async function testAI(){if(S.provider==='demo')return toast('Demo Mode đang hoạt động.');const out=await askAI('Trả lời đúng một câu ngắn bằng tiếng Việt để xác nhận Lion AI đang hoạt động.','assistant');$('#statusChip').textContent=out?'AI đang hoạt động':'AI chưa phản hồi';if(out)toast('AI hoạt động: '+out)}
function toggleBot(){S.run=!S.run;$('#startBtn').textContent=S.run?'Dừng bot':'Bắt đầu bot';$('#liveChip').classList.toggle('live',S.run);$('#liveText').textContent=S.run?'LIVE • Demo đang chạy':'TikTok chưa kết nối — Demo Mode';$('#hostState').textContent=S.run?'AI host đang trực':'Đang chờ bắt đầu';clearInterval(S.timer);if(S.run){if(!S.comments.length)addComment();S.timer=setInterval(addComment,5600);toast('Bot đã bắt đầu.')}else{stopAudio();toast('Bot đã dừng.')}metrics()}
function bind(){
  $$('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>switchView(b.dataset.jump));
  $$('#themeSwitch button').forEach(b=>b.onclick=()=>{S.theme=b.dataset.theme;persist();applyTheme()});
  $$('[data-mode]').forEach(b=>b.onclick=()=>{$$('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));S.mode=b.dataset.mode;persist();toast(S.mode==='auto'?'Tự động: AI sẽ trả lời và đọc theo hàng đợi.':'Duyệt tay: bạn kiểm tra trước khi đọc.')});
  $$('.tone').forEach(b=>b.onclick=()=>{$$('.tone').forEach(x=>x.classList.toggle('active',x===b));S.tone=b.dataset.tone;persist()});
  $('#startBtn').onclick=toggleBot;$('#demoBtn').onclick=addComment;$('#clearBtn').onclick=()=>{S.comments=[];S.selected=null;$('#reply').value='';$('#selected').textContent='Chọn một bình luận để AI xử lý.';renderComments();metrics()};
  $('#rewriteBtn').onclick=()=>generateReply(S.selected,false);$('#speakBtn').onclick=()=>enqueueSpeak($('#reply').value.trim(),false);$('#testAiBtn').onclick=testAI;
  $('#newProdBtn').onclick=newProduct;$('#saveProdBtn').onclick=saveProduct;$('#deleteProdBtn').onclick=deleteProduct;$('#clearHistoryBtn').onclick=()=>{S.history=[];persist();renderHistory();toast('Đã xóa lịch sử chat.')};
  $('#provider').onchange=e=>{S.provider=e.target.value;persist();syncSettings()};$('#model').onchange=e=>{S.model=e.target.value.trim();persist()};$('#ttsVoice').onchange=e=>{S.voice=e.target.value;persist();syncVoiceUI()};$('#customVoiceId').onchange=e=>{S.customVoiceId=e.target.value.trim();persist()};$('#rate').oninput=e=>{S.rate=Number(e.target.value);persist()};
  $('#refreshVoicesBtn').onclick=()=>{refreshVoicePicker();toast('Đã quét lại giọng tiếng Việt.')};$('#browserVoice').onchange=e=>{LionVietnameseVoices.setSelected(e.target.value);refreshVoicePicker()};
  $('#voiceTestBtn').onclick=()=>enqueueSpeak('Xin chào, đây là giọng hội thoại của Lion AI. Mình sẽ nói tiếng Việt tự nhiên, rõ ràng, ấm áp và giống một cuộc trò chuyện thật hơn.',false);
  $('#testBrowserVoiceBtn').onclick=async()=>{try{await LionVietnameseVoices.speak('Xin chào, đây là giọng tiếng Việt trên thiết bị của bạn.',S.rate);toast('Giọng Việt trên thiết bị hoạt động tốt.')}catch(e){toast(e.message)}};
  $('#playVoiceSampleBtn').onclick=()=>{const a=$('#voiceSampleAudio');a.currentTime=0;a.play().catch(()=>toast('Trình duyệt chưa cho phép phát audio. Hãy bấm nút phát trên thanh audio.'))};
  $('#useConversationPresetBtn').onclick=()=>{S.voice='lion-conversation';persist();syncVoiceUI();toast('Đã chọn preset Lion Hội thoại.')};
  window.addEventListener('lionvoiceschanged',refreshVoicePicker);
  window.addEventListener('beforeunload',()=>{if(S.sampleUrl)URL.revokeObjectURL(S.sampleUrl)});
}
function init(){renderPalette();applyTheme();bind();renderProducts();if(S.products.length)loadProduct(S.active||S.products[0].id);renderComments();renderHistory();syncSettings();refreshVoicePicker();setupVoiceSample();$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===S.mode));$$('.tone').forEach(b=>b.classList.toggle('active',b.dataset.tone===S.tone));metrics()}
document.addEventListener('DOMContentLoaded',init);